/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HashBot {
        "apiurl": string;
        "chatbotheight": number;
        "chatbotwidth": number;
        "iconsize": number;
    }
}
declare global {
    interface HTMLHashBotElement extends Components.HashBot, HTMLStencilElement {
    }
    var HTMLHashBotElement: {
        prototype: HTMLHashBotElement;
        new (): HTMLHashBotElement;
    };
    interface HTMLElementTagNameMap {
        "hash-bot": HTMLHashBotElement;
    }
}
declare namespace LocalJSX {
    interface HashBot {
        "apiurl"?: string;
        "chatbotheight"?: number;
        "chatbotwidth"?: number;
        "iconsize"?: number;
    }
    interface IntrinsicElements {
        "hash-bot": HashBot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hash-bot": LocalJSX.HashBot & JSXBase.HTMLAttributes<HTMLHashBotElement>;
        }
    }
}
